
(in-package :beng)

(defparameter *doc1* "The fight against COVID-19 has launched a thousand military metaphors in the British press.")
(defparameter *doc2* "The \"greatest challenge since the Second World War\", \"the frontline\", the virus is an \"invisible enemy\", and so forth.")
(defparameter *doc3* "US citizens feel besieged and under threat as we retreat to our foxholes.")

(let ((cxn-set (make-instance 'construction-set))
      (car nil))
  (deactivate-monitor trace-fcg)
  (setf (right-pole-structure *saved-cfs*)
      `((meta
         (information-type statement)
         (temporal-frame ?temporal-frame))
        (topic
         (phrase ?topic-phrase))
        (state-activity
         (phrase ?state-activity-phrase)
         (type ?type-of-state-activity)
         (manner (phrase ?manner-phrase-1))
         (location (phrase ?location-phrase-2)))))
  (multiple-value-bind (cars other)
      (fcg-apply (make-instance 'construction
                                :name 'topic-comment-cxn
                                :left-pole '((?clause
                                              (information-structure (==1 (topic ?topic)
                                                                          (comment ?comment)))
                                              (footprints (==0 topic-comment-cxn)))
                                             ((J ?clause)
                                              (footprints (== topic-comment-cxn))))
                                :right-pole '((topic
                                               (phrase  ?topic))
                                              (state-activity
                                               (phrase ?comment))))
                 *saved-cfs* '->)
    (add-element (make-html (first cars)))))

(add-element (make-html *saved-cfs*))




(defparameter *sample-text* "The frontline troops are running out of protective gear (PPE), ammunition (beds) and heavy equipment (ventilators). Supply lines are stretched thin. Meanwhile, the country's leadership - the prime minister, secretary of state for health and the chief medical officer - are self-isolating in their bunkers where they cannot be functioning at 100%. The enemy moves among us unseen.")

(comprehend "The frontline troops are running out of protective gear.") ; (PPE), ammunition (beds) and heavy equipment (ventilators).")

(in-package :s-dot)

(wi:s-dot->image '(graph ((rankdir "LR"))
                   (node ((id "a")
                          (label "frontline troops")))
                   (node ((id "b")
                          (label "protective gear (PPE), ammunition (beds) and heavy equipment (ventilators)")))
                   (edge ((from "a") (to "b") (label "are running out of"))))
                 :open t)

(wi:s-dot->image '(graph ((rankdir "LR"))
                   (node ((id "a")
                          (label "US citizens")))
                   (node ((id "b")
                          (label "besieged and under threat")))
                   (edge ((from "a") (to "b") (label "feel"))))
                 :open t)

(wi:s-dot->image '(graph ()
                         (cluster ((id "entity1")
                                   (style "filled") (fillcolor "#EEEEFF") (fontcolor "#900000")
                                   (label "the country's leadership"))
                                  (cluster ((id "e1isa")
                                            (style "filled")
                                            (label "ISA") (fillcolor "#FFFFFF"))
                                           (node ((id "e1isa1")
                                                  (label "the prime minister, secretary of state for health and the chief medical officer"))))
                                  (cluster ((id "e1doing")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "STATE/ACTIVITY"))
                                           (node ((id "e1doing1")
                                                  (label "self-isolating")))
                                           (node ((id "e1doing2")
                                                  (label "in their bunkers")
                                                  (shape "diamond")))
                                           (edge ((from "e1doing1") (to "e1doing2") (label "LOCATION"))))
                                  (cluster ((id "e1cannot")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "CANNOT"))
                                           (node ((id "e1cannot1")
                                                  (label "functioning at 100%")))))
                         (cluster ((id "entity2")
                                   (style "filled") (fillcolor "#EEEEFF") (fontcolor "#900000")
                                   (label "the frontline troops"))
                                  (cluster ((id "e2doing")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "STATE/ACTIVITY"))
                                           (node ((id "e2doin1") (label "running out of protective gear (PPE),\\nammunition (beds) and heavy equipment (ventilators)")))))
                         (cluster ((id "entity3")
                                   (style "filled") (fillcolor "#EEEEFF") (fontcolor "#900000")
                                   (label "the enemy"))
                                  (cluster ((id "e3isa")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "ISA"))
                                           (node ((id "e3isa1") (label "the virus"))))
                                  (cluster ((id "e3doing")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "STATE/ACTIVITY"))
                                           (node ((id "e3doing1") (label "moving")))
                                           (node ((id "e3doing2") (label "among us") (shape "diamond")))
                                           (edge ((from "e3doing1") (to "e3doing2") (label "LOCATION"))))
                                  (cluster ((id "e3properties")
                                            (style "filled") (fillcolor "#FFFFFF")
                                            (label "HAS-PROPERTIES"))
                                           (node ((id "e3hasproperties1") (label "unseen"))))))
                 :open t)